# Generated by Django 6.0.5 on 2026-05-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking_number', models.TextField(unique=True)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('customer_name', models.TextField()),
                ('customer_phone', models.TextField()),
                ('customer_email', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.TextField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
    ]
