# Generated by Django 6.0.2 on 2026-04-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_number', models.TextField(unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.TextField()),
                ('customer_phone', models.TextField()),
                ('customer_email', models.TextField(blank=True, null=True)),
                ('delivery_address', models.TextField()),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('vendor_notes', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validée'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING')),
                ('tracking_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
