# Generated by Django 6.0.2 on 2026-04-07 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('on-break', 'On Break'), ('offline', 'Offline')], default='inactive', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('motorcycle', 'Motorcycle'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], max_length=20, null=True)),
                ('vehicle_license_plate', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('vehicle_capacity_kg', models.IntegerField(default=50)),
                ('vehicle_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20, null=True)),
                ('vehicle_last_inspection', models.DateTimeField(blank=True, null=True)),
                ('license_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('license_verified_at', models.DateTimeField(blank=True, null=True)),
                ('id_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('id_verified_at', models.DateTimeField(blank=True, null=True)),
                ('insurance_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('insurance_verified_at', models.DateTimeField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('registration_expiry_date', models.DateField(blank=True, null=True)),
                ('registration_verified_at', models.DateTimeField(blank=True, null=True)),
                ('background_check_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('background_check_expiry_date', models.DateField(blank=True, null=True)),
                ('background_check_verified_at', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('avg_delivery_time_minutes', models.IntegerField(default=0)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('earnings_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('earnings_this_week', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_payout_date', models.DateTimeField(blank=True, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
    ]
