# Generated by Django 6.0.5 on 2026-05-13 17:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingFraudCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('level', models.TextField()),
                ('signals', models.JSONField(default=list)),
                ('recommendation', models.TextField()),
                ('ai_reasoning', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'booking_fraud_checks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderFraudCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('level', models.TextField()),
                ('signals', models.JSONField(default=list)),
                ('recommendation', models.TextField()),
                ('ai_reasoning', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'order_fraud_checks',
                'managed': False,
            },
        ),
    ]
