import { Business } from '@/types/business';
import { Product } from '@/types/product';
import { Review } from '@/types/review';
import { Report } from '@/types/report';
import { AdminUser } from '@/types/admin';
import { AnalyticsMetric, TopSearchTerm, CategoryDemand, KPIData } from '@/types/analytics';

// Mock admin users
export const mockAdminUsers: AdminUser[] = [
  {
    id: '1',
    email: 'admin@ro2ya.com',
    name: 'Sarah Ahmed',
    role: 'admin',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    department: 'Management',
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2024-02-15'),
    lastLoginAt: new Date(),
  },
  {
    id: '2',
    email: 'moderator@ro2ya.com',
    name: 'Omar Hassan',
    role: 'moderator',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Omar',
    department: 'Moderation',
    createdAt: new Date('2023-03-20'),
    updatedAt: new Date('2024-02-14'),
    lastLoginAt: new Date(),
  },
];

// Mock businesses
export const mockBusinesses: Business[] = [
  {
    id: '1',
    name: 'Al-Reef Restaurant',
    ownerName: 'Ahmed Al-Mansouri',
    ownerEmail: 'ahmed@alreef.com',
    category: 'Restaurants & Cafes',
    description: 'Traditional Arabian restaurant with authentic cuisine',
    location: { latitude: 25.2048, longitude: 55.2708 },
    address: 'Dubai Marina',
    city: 'Dubai',
    country: 'UAE',
    phone: '+971-4-123-4567',
    website: 'www.alreef.com',
    status: 'approved',
    verificationStatus: 'verified',
    riskScore: 15,
    riskLevel: 'low',
    averageRating: 4.8,
    totalReviews: 234,
    totalProducts: 45,
    totalReports: 2,
    documentsVerified: true,
    badge: 'verified',
    suspended: false,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2024-02-15'),
    verifiedAt: new Date('2023-02-01'),
    lastActivityAt: new Date(),
  },
  {
    id: '2',
    name: 'Tech Gadgets Store',
    ownerName: 'Fatima Al-Mazrouei',
    ownerEmail: 'fatima@techgadgets.ae',
    category: 'Technology',
    description: 'Premium electronics and gadgets retailer',
    location: { latitude: 25.1972, longitude: 55.2744 },
    address: 'Downtown Dubai',
    city: 'Dubai',
    country: 'UAE',
    phone: '+971-4-234-5678',
    website: 'www.techgadgets.ae',
    status: 'pending',
    verificationStatus: 'pending',
    riskScore: 35,
    riskLevel: 'medium',
    averageRating: 4.2,
    totalReviews: 89,
    totalProducts: 156,
    totalReports: 5,
    documentsVerified: false,
    suspended: false,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '3',
    name: 'Beauty Boutique Plus',
    ownerName: 'Mariam Al-Ketbi',
    ownerEmail: 'mariam@beautyboutique.com',
    category: 'Retail Shops',
    description: 'Luxury beauty and cosmetics store',
    location: { latitude: 25.1856, longitude: 55.2705 },
    address: 'Dubai Hills',
    city: 'Dubai',
    country: 'UAE',
    phone: '+971-4-345-6789',
    website: 'www.beautyboutique.ae',
    status: 'approved',
    verificationStatus: 'verified',
    riskScore: 8,
    riskLevel: 'low',
    averageRating: 4.9,
    totalReviews: 567,
    totalProducts: 234,
    totalReports: 0,
    documentsVerified: true,
    badge: 'verified',
    suspended: false,
    createdAt: new Date('2022-06-20'),
    updatedAt: new Date('2024-02-12'),
    verifiedAt: new Date('2022-07-15'),
    lastActivityAt: new Date(),
  },
];

// Mock products
export const mockProducts: Product[] = [
  {
    id: '1',
    businessId: '1',
    businessName: 'Al-Reef Restaurant',
    name: 'Shawarma Plate',
    description: 'Traditional chicken shawarma with tahini sauce',
    category: 'Food & Beverages',
    price: 25,
    currency: 'AED',
    images: ['https://images.unsplash.com/photo-1555939594-58d7cb561701'],
    status: 'visible',
    totalReports: 0,
    flaggedCount: 0,
    averageRating: 4.7,
    reviewCount: 145,
    visibility: 'public',
    featured: true,
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: '2',
    businessId: '2',
    businessName: 'Tech Gadgets Store',
    name: 'Wireless Earbuds Pro',
    description: 'Premium wireless earbuds with noise cancellation',
    category: 'Electronics',
    price: 299,
    currency: 'AED',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e'],
    status: 'flagged',
    totalReports: 3,
    flaggedCount: 2,
    averageRating: 3.8,
    reviewCount: 42,
    visibility: 'public',
    featured: false,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-10'),
  },
];

// Mock reviews
export const mockReviews: Review[] = [
  {
    id: '1',
    productId: '1',
    productName: 'Shawarma Plate',
    businessId: '1',
    businessName: 'Al-Reef Restaurant',
    userId: 'user1',
    userName: 'Mohammed Al-Mansoori',
    rating: 5,
    title: 'Excellent taste!',
    content: 'The best shawarma I have ever tasted. Fresh ingredients and amazing seasoning.',
    status: 'visible',
    spamScore: 5,
    riskLevel: 'low',
    flagged: false,
    flagCount: 0,
    helpful: 234,
    unhelpful: 5,
    verified: true,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '2',
    productId: '2',
    productName: 'Wireless Earbuds Pro',
    businessId: '2',
    businessName: 'Tech Gadgets Store',
    userId: 'user2',
    userName: 'Layla Al-Kaabi',
    rating: 2,
    title: 'Poor quality',
    content: 'Not as described. Battery dies quickly.',
    status: 'visible',
    spamScore: 45,
    riskLevel: 'medium',
    flagged: true,
    flagCount: 2,
    helpful: 12,
    unhelpful: 3,
    verified: true,
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-08'),
  },
];

// Mock reports
export const mockReports: Report[] = [
  {
    id: 'REP001',
    type: 'product',
    reporterId: 'user3',
    reporterName: 'Hassan Al-Mansoori',
    reporterEmail: 'hassan@example.com',
    targetId: '2',
    targetName: 'Wireless Earbuds Pro',
    targetType: 'product',
    reason: 'Product quality issue',
    description: 'The product does not match the description on the listing',
    evidence: ['https://example.com/photo1.jpg'],
    status: 'investigating',
    priority: 'high',
    assignedAdminId: '2',
    assignedAdminName: 'Omar Hassan',
    createdAt: new Date('2024-02-12'),
    updatedAt: new Date('2024-02-13'),
    investigationStartedAt: new Date('2024-02-13'),
  },
  {
    id: 'REP002',
    type: 'business',
    reporterId: 'user4',
    reporterName: 'Noor Al-Mazrouei',
    reporterEmail: 'noor@example.com',
    targetId: '2',
    targetName: 'Tech Gadgets Store',
    targetType: 'business',
    reason: 'Suspected fraudulent business',
    description: 'Multiple customers reporting similar issues',
    status: 'pending',
    priority: 'critical',
    createdAt: new Date('2024-02-14'),
    updatedAt: new Date('2024-02-14'),
  },
];

// Mock analytics data
export const mockAnalyticsMetrics: AnalyticsMetric[] = [
  { date: 'Jan 1', value: 12000, label: 'Users' },
  { date: 'Jan 8', value: 14500, label: 'Users' },
  { date: 'Jan 15', value: 16200, label: 'Users' },
  { date: 'Jan 22', value: 18900, label: 'Users' },
  { date: 'Jan 29', value: 21200, label: 'Users' },
  { date: 'Feb 5', value: 23800, label: 'Users' },
  { date: 'Feb 12', value: 25600, label: 'Users' },
];

export const mockTopSearchTerms: TopSearchTerm[] = [
  { term: 'coffee shops', searchCount: 45200, resultCount: 234, conversionCount: 3420, conversionRate: 7.5 },
  { term: 'pizza delivery', searchCount: 38900, resultCount: 156, conversionCount: 2934, conversionRate: 7.5 },
  { term: 'hair salon', searchCount: 32100, resultCount: 89, conversionCount: 2248, conversionRate: 7.0 },
  { term: 'gyms near me', searchCount: 28500, resultCount: 123, conversionCount: 1995, conversionRate: 7.0 },
  { term: 'restaurants', searchCount: 25600, resultCount: 456, conversionCount: 1792, conversionRate: 7.0 },
];

export const mockCategoryDemand: CategoryDemand[] = [
  { category: 'Restaurants & Cafes', searchCount: 145000, productCount: 2340, businessCount: 1200, demandTrend: 'up', percentageChange: 12.5 },
  { category: 'Retail Shops', searchCount: 98500, productCount: 5600, businessCount: 850, demandTrend: 'stable', percentageChange: 2.1 },
  { category: 'Healthcare', searchCount: 76200, productCount: 1200, businessCount: 650, demandTrend: 'up', percentageChange: 8.3 },
  { category: 'Technology', searchCount: 67800, productCount: 3400, businessCount: 420, demandTrend: 'down', percentageChange: -5.2 },
  { category: 'Education', searchCount: 54300, productCount: 890, businessCount: 320, demandTrend: 'up', percentageChange: 15.1 },
];

export const mockKPIs: KPIData[] = [
  { label: 'Users', value: 25600, change: 120, percentageChange: 0.5, trend: 'up', icon: 'users' },
  { label: 'New Users Today', value: 42, change: 5, percentageChange: 13.5, trend: 'up', icon: 'user-plus' },
  { label: 'Total Orders', value: 12450, change: 450, percentageChange: 3.8, trend: 'up', icon: 'shopping-bag' },
  { label: 'Pending Orders', value: 125, change: -12, percentageChange: -8.7, trend: 'down', icon: 'clock' },
  { label: 'Ongoing Orders', value: 84, change: 8, percentageChange: 10.5, trend: 'up', icon: 'truck' },
  { label: 'Completed Orders', value: 11240, change: 380, percentageChange: 3.5, trend: 'up', icon: 'check-circle' },
  { label: 'Cancelled Orders', value: 101, change: 2, percentageChange: 2.0, trend: 'stable', icon: 'x-circle' },
  { label: 'Total Merchants', value: 5234, change: 32, percentageChange: 0.6, trend: 'up', icon: 'store' },
  { label: 'Pending Merchants', value: 45, change: -3, percentageChange: -6.2, trend: 'down', icon: 'user-check' },
  { label: 'Merchant Types', value: 12, change: 0, percentageChange: 0, trend: 'stable', icon: 'settings-2' },
  { label: 'Categories', value: 48, change: 2, percentageChange: 4.3, trend: 'up', icon: 'layers' },
  { label: 'Subcategories', value: 156, change: 5, percentageChange: 3.3, trend: 'up', icon: 'layout' },
  { label: 'Brands', value: 840, change: 12, percentageChange: 1.4, trend: 'up', icon: 'tag' },
  { label: 'Products', value: 145200, change: 1240, percentageChange: 0.9, trend: 'up', icon: 'box' },
  { label: 'Deals', value: 342, change: 15, percentageChange: 4.6, trend: 'up', icon: 'percent' },
  { label: 'Coupons', value: 124, change: -5, percentageChange: -3.8, trend: 'down', icon: 'ticket' },
  { label: 'New Reviews Today', value: 87, change: 12, percentageChange: 16.0, trend: 'up', icon: 'star' },
];
