import { ModerationProduct, ModerationStats } from '@/types/moderation';

export const mockModerationProducts: ModerationProduct[] = [
  {
    id: 'mp001',
    name: 'AirMax Pro Wireless Headphones',
    description: 'Premium noise-cancelling headphones with 30hr battery life. Crystal clear sound with deep bass.',
    category: 'Electronics',
    price: 89.99,
    currency: 'USD',
    stock: 150,
    images: ['/products/headphones1.jpg', '/products/headphones2.jpg'],
    sellerId: 's001',
    sellerName: 'Marcus Johnson',
    businessName: 'SoundPro Electronics',
    sellerRegisteredAt: '2023-03-12',
    sellerTrustScore: 92,
    sellerTotalProducts: 24,
    status: 'pending',
    riskLevel: 'low',
    riskIndicators: [],
    reports: [],
    totalReports: 0,
    submittedAt: '2025-03-14T09:22:00Z',
    averageRating: 4.7,
    totalSales: 312,
  },
  {
    id: 'mp002',
    name: 'iPhone 16 Pro Max – Brand New',
    description: 'Sealed box iPhone 16 Pro Max 512GB. Selling for $199 only! Limited stock.',
    category: 'Electronics',
    price: 199,
    currency: 'USD',
    stock: 5,
    images: ['/products/iphone1.jpg'],
    sellerId: 's002',
    sellerName: 'Ali Hassan',
    businessName: 'QuickDeals99',
    sellerRegisteredAt: '2025-02-28',
    sellerTrustScore: 28,
    sellerTotalProducts: 3,
    status: 'flagged',
    riskLevel: 'high',
    riskIndicators: [
      { type: 'new_seller', label: 'New Seller (< 30 days)', severity: 'medium' },
      { type: 'low_price', label: 'Suspiciously Low Price', severity: 'high' },
      { type: 'suspicious_keywords', label: 'Suspicious Keywords Detected', severity: 'high' },
    ],
    reports: [
      { id: 'r001', reason: 'fake_product', label: 'Fake Product', reportedBy: 'user_44', reportedAt: '2025-03-13T14:00:00Z' },
      { id: 'r002', reason: 'wrong_price', label: 'Wrong Price', reportedBy: 'user_89', reportedAt: '2025-03-13T18:30:00Z' },
    ],
    totalReports: 2,
    submittedAt: '2025-03-12T11:00:00Z',
    averageRating: 1.2,
    totalSales: 0,
  },
  {
    id: 'mp003',
    name: 'Handmade Leather Wallet',
    description: 'Genuine full-grain leather bifold wallet. Slim design, RFID blocking. Handcrafted in Italy.',
    category: 'Fashion',
    price: 45.00,
    currency: 'USD',
    stock: 80,
    images: ['/products/wallet1.jpg', '/products/wallet2.jpg', '/products/wallet3.jpg'],
    sellerId: 's003',
    sellerName: 'Sofia Ricci',
    businessName: 'ArtisanLeather Co.',
    sellerRegisteredAt: '2022-07-20',
    sellerTrustScore: 97,
    sellerTotalProducts: 61,
    status: 'pending',
    riskLevel: 'low',
    riskIndicators: [],
    reports: [],
    totalReports: 0,
    submittedAt: '2025-03-15T08:10:00Z',
    averageRating: 4.9,
    totalSales: 1420,
  },
  {
    id: 'mp004',
    name: 'Luxury Perfume 200ml',
    description: 'Designer fragrance – inspired by top brands. Long lasting 12h+ scent. Men & Women.',
    category: 'Beauty',
    price: 12.50,
    currency: 'USD',
    stock: 200,
    images: ['/products/perfume1.jpg'],
    sellerId: 's004',
    sellerName: 'Youssef Nabil',
    businessName: 'FragranceWorld',
    sellerRegisteredAt: '2024-11-01',
    sellerTrustScore: 44,
    sellerTotalProducts: 8,
    status: 'reported',
    riskLevel: 'high',
    riskIndicators: [
      { type: 'suspicious_keywords', label: '"Inspired by" = Counterfeit Risk', severity: 'high' },
      { type: 'low_price', label: 'Unrealistically Low Price', severity: 'high' },
      { type: 'too_many_reports', label: 'Multiple User Reports', severity: 'high' },
    ],
    reports: [
      { id: 'r003', reason: 'fake_product', label: 'Fake Product', reportedBy: 'user_12', reportedAt: '2025-03-10T09:00:00Z' },
      { id: 'r004', reason: 'misleading_description', label: 'Misleading Description', reportedBy: 'user_33', reportedAt: '2025-03-11T11:30:00Z' },
      { id: 'r005', reason: 'illegal_item', label: 'Illegal Item', reportedBy: 'user_55', reportedAt: '2025-03-12T16:00:00Z' },
    ],
    totalReports: 3,
    submittedAt: '2025-03-09T14:22:00Z',
    averageRating: 2.1,
    totalSales: 45,
  },
  {
    id: 'mp005',
    name: 'Standing Desk Converter',
    description: 'Ergonomic sit-stand desk converter. Adjustable height 15cm–45cm. Supports up to 15kg.',
    category: 'Office',
    price: 129.00,
    currency: 'USD',
    stock: 35,
    images: ['/products/desk1.jpg'],
    sellerId: 's005',
    sellerName: 'Lena Schreiber',
    businessName: 'ErgoPro Office',
    sellerRegisteredAt: '2021-04-15',
    sellerTrustScore: 88,
    sellerTotalProducts: 42,
    status: 'approved',
    riskLevel: 'low',
    riskIndicators: [],
    reports: [],
    totalReports: 0,
    submittedAt: '2025-03-10T07:00:00Z',
    reviewedAt: '2025-03-10T10:30:00Z',
    reviewedBy: 'Admin Sarah',
    averageRating: 4.5,
    totalSales: 234,
  },
  {
    id: 'mp006',
    name: 'Yoga Mat Premium Non-Slip',
    description: 'Extra thick 6mm yoga mat. Eco-friendly TPE material. Includes carrying strap.',
    category: 'Sports',
    price: 34.99,
    currency: 'USD',
    stock: 120,
    images: ['/products/yoga1.jpg'],
    sellerId: 's006',
    sellerName: 'Priya Sharma',
    businessName: 'ZenFitness',
    sellerRegisteredAt: '2023-01-10',
    sellerTrustScore: 79,
    sellerTotalProducts: 18,
    status: 'pending',
    riskLevel: 'low',
    riskIndicators: [],
    reports: [],
    totalReports: 0,
    submittedAt: '2025-03-15T10:00:00Z',
    averageRating: 4.3,
    totalSales: 589,
  },
  {
    id: 'mp007',
    name: 'Mystery Box - $500 Value!!',
    description: 'Buy this mystery box worth $500 for only $9.99. Contains electronics, jewelry, and more!',
    category: 'Other',
    price: 9.99,
    currency: 'USD',
    stock: 999,
    images: ['/products/mystery1.jpg'],
    sellerId: 's007',
    sellerName: 'Unknown Seller',
    businessName: 'MegaDeals247',
    sellerRegisteredAt: '2025-03-01',
    sellerTrustScore: 12,
    sellerTotalProducts: 1,
    status: 'flagged',
    riskLevel: 'high',
    riskIndicators: [
      { type: 'new_seller', label: 'New Seller (< 30 days)', severity: 'medium' },
      { type: 'low_price', label: 'Suspiciously Low Price', severity: 'high' },
      { type: 'suspicious_keywords', label: 'Spam Keywords Detected', severity: 'high' },
      { type: 'repeated_images', label: 'Stock Image Detected', severity: 'medium' },
    ],
    reports: [
      { id: 'r006', reason: 'spam_listing', label: 'Spam Listing', reportedBy: 'user_77', reportedAt: '2025-03-14T08:00:00Z' },
    ],
    totalReports: 1,
    submittedAt: '2025-03-14T06:00:00Z',
    averageRating: 0,
    totalSales: 0,
  },
  {
    id: 'mp008',
    name: 'Coffee Grinder – Burr Mill',
    description: 'Professional burr grinder with 18 grind settings. Consistent grind for espresso to cold brew.',
    category: 'Kitchen',
    price: 67.00,
    currency: 'USD',
    stock: 55,
    images: ['/products/grinder1.jpg'],
    sellerId: 's008',
    sellerName: 'Tomás Herrera',
    businessName: 'BrewCraft',
    sellerRegisteredAt: '2022-09-05',
    sellerTrustScore: 85,
    sellerTotalProducts: 29,
    status: 'pending',
    riskLevel: 'low',
    riskIndicators: [],
    reports: [],
    totalReports: 0,
    submittedAt: '2025-03-15T12:45:00Z',
    averageRating: 4.6,
    totalSales: 201,
  },
  {
    id: 'mp009',
    name: 'Counterfeit Nike Air Force 1',
    description: '1:1 Clone Nike shoes. Exact replica with original box.',
    category: 'Fashion',
    price: 25.00,
    currency: 'USD',
    stock: 500,
    images: ['/products/shoes1.jpg'],
    sellerId: 's009',
    sellerName: 'Chen Wei',
    businessName: 'CopyKick Store',
    sellerRegisteredAt: '2025-02-15',
    sellerTrustScore: 5,
    sellerTotalProducts: 4,
    status: 'rejected',
    riskLevel: 'high',
    riskIndicators: [
      { type: 'suspicious_keywords', label: 'Counterfeit Language Detected', severity: 'high' },
      { type: 'new_seller', label: 'New Seller', severity: 'medium' },
      { type: 'duplicate_product', label: 'Duplicate Listing Detected', severity: 'high' },
    ],
    reports: [
      { id: 'r007', reason: 'fake_product', label: 'Fake Product', reportedBy: 'user_22', reportedAt: '2025-03-13T07:00:00Z' },
      { id: 'r008', reason: 'illegal_item', label: 'Illegal Item', reportedBy: 'user_66', reportedAt: '2025-03-13T09:00:00Z' },
    ],
    totalReports: 2,
    submittedAt: '2025-03-12T20:00:00Z',
    reviewedAt: '2025-03-13T10:00:00Z',
    reviewedBy: 'Admin James',
    rejectionReason: 'Counterfeit product – trademark infringement detected.',
    averageRating: 0,
    totalSales: 12,
  },
  {
    id: 'mp010',
    name: 'Portable Solar Charger 20000mAh',
    description: 'Solar power bank with dual USB output. Perfect for hiking and camping. Water resistant.',
    category: 'Electronics',
    price: 42.00,
    currency: 'USD',
    stock: 75,
    images: ['/products/solar1.jpg'],
    sellerId: 's010',
    sellerName: 'James Park',
    businessName: 'OutdoorTech',
    sellerRegisteredAt: '2022-06-20',
    sellerTrustScore: 76,
    sellerTotalProducts: 15,
    status: 'pending',
    riskLevel: 'medium',
    riskIndicators: [
      { type: 'new_seller', label: 'Moderate Seller Score', severity: 'medium' },
    ],
    reports: [],
    totalReports: 0,
    submittedAt: '2025-03-15T09:30:00Z',
    averageRating: 4.2,
    totalSales: 87,
  },
];

export const mockModerationStats: ModerationStats = {
  pendingReview: mockModerationProducts.filter(p => p.status === 'pending').length,
  approvedToday: 7,
  rejectedToday: 3,
  reported: mockModerationProducts.filter(p => p.status === 'reported' || p.totalReports > 0).length,
  highRisk: mockModerationProducts.filter(p => p.riskLevel === 'high').length,
  totalProducts: mockModerationProducts.length,
};