import { Product } from '@/types/product';

export const mockProducts: Product[] = [
  {
    id: 'p001',
    businessId: 'b001',
    businessName: 'SoundPro Electronics',
    name: 'AirMax Pro Wireless Headphones',
    description: 'Premium noise-cancelling headphones with 30hr battery life.',
    category: 'Electronics',
    price: 89.99,
    currency: 'USD',
    images: ['/products/headphones1.jpg'],
    status: 'visible',
    totalReports: 0,
    flaggedCount: 0,
    averageRating: 4.7,
    reviewCount: 312,
    visibility: 'public',
    featured: true,
    featuredUntil: new Date('2025-06-01'),
    createdAt: new Date('2024-11-10'),
    updatedAt: new Date('2025-02-20'),
  },
  {
    id: 'p002',
    businessId: 'b002',
    businessName: 'ArtisanLeather Co.',
    name: 'Handmade Leather Wallet',
    description: 'Genuine full-grain leather bifold wallet. RFID blocking. Handcrafted in Italy.',
    category: 'Fashion',
    price: 45.00,
    currency: 'USD',
    images: ['/products/wallet1.jpg'],
    status: 'visible',
    totalReports: 0,
    flaggedCount: 0,
    averageRating: 4.9,
    reviewCount: 1420,
    visibility: 'public',
    featured: false,
    createdAt: new Date('2023-07-20'),
    updatedAt: new Date('2025-01-15'),
  },
  {
    id: 'p003',
    businessId: 'b003',
    businessName: 'QuickDeals99',
    name: 'iPhone 16 Pro Max – Brand New',
    description: 'Sealed box iPhone 16 Pro Max 512GB. Selling for $199 only!',
    category: 'Electronics',
    price: 199.00,
    currency: 'USD',
    images: ['/products/iphone1.jpg'],
    status: 'flagged',
    totalReports: 2,
    flaggedCount: 3,
    averageRating: 1.2,
    reviewCount: 4,
    visibility: 'public',
    featured: false,
    createdAt: new Date('2025-03-12'),
    updatedAt: new Date('2025-03-13'),
  },
  {
    id: 'p004',
    businessId: 'b004',
    businessName: 'FragranceWorld',
    name: 'Luxury Perfume 200ml',
    description: 'Designer fragrance inspired by top brands. Long lasting 12h+ scent.',
    category: 'Beauty',
    price: 12.50,
    currency: 'USD',
    images: ['/products/perfume1.jpg'],
    status: 'banned',
    totalReports: 3,
    flaggedCount: 5,
    averageRating: 2.1,
    reviewCount: 22,
    visibility: 'hidden',
    featured: false,
    createdAt: new Date('2025-01-09'),
    updatedAt: new Date('2025-03-10'),
    lastModeratedAt: new Date('2025-03-13'),
  },
  {
    id: 'p005',
    businessId: 'b005',
    businessName: 'ErgoPro Office',
    name: 'Standing Desk Converter',
    description: 'Ergonomic sit-stand desk converter. Adjustable height 15–45cm. Supports 15kg.',
    category: 'Office',
    price: 129.00,
    currency: 'USD',
    images: ['/products/desk1.jpg'],
    status: 'visible',
    totalReports: 0,
    flaggedCount: 0,
    averageRating: 4.5,
    reviewCount: 234,
    visibility: 'public',
    featured: true,
    featuredUntil: new Date('2025-05-01'),
    createdAt: new Date('2023-04-15'),
    updatedAt: new Date('2025-02-01'),
  },
  {
    id: 'p006',
    businessId: 'b006',
    businessName: 'ZenFitness',
    name: 'Yoga Mat Premium Non-Slip',
    description: 'Extra thick 6mm yoga mat. Eco-friendly TPE material. Includes carrying strap.',
    category: 'Sports',
    price: 34.99,
    currency: 'USD',
    images: ['/products/yoga1.jpg'],
    status: 'visible',
    totalReports: 0,
    flaggedCount: 0,
    averageRating: 4.3,
    reviewCount: 589,
    visibility: 'public',
    featured: false,
    createdAt: new Date('2023-01-10'),
    updatedAt: new Date('2024-12-20'),
  },
  {
    id: 'p007',
    businessId: 'b007',
    businessName: 'MegaDeals247',
    name: 'Mystery Box - $500 Value!!',
    description: 'Buy this mystery box worth $500 for only $9.99!',
    category: 'Other',
    price: 9.99,
    currency: 'USD',
    images: ['/products/mystery1.jpg'],
    status: 'flagged',
    totalReports: 1,
    flaggedCount: 4,
    averageRating: 0,
    reviewCount: 0,
    visibility: 'public',
    featured: false,
    createdAt: new Date('2025-03-14'),
    updatedAt: new Date('2025-03-14'),
  },
  {
    id: 'p008',
    businessId: 'b008',
    businessName: 'BrewCraft',
    name: 'Coffee Grinder – Burr Mill',
    description: 'Professional burr grinder with 18 grind settings.',
    category: 'Kitchen',
    price: 67.00,
    currency: 'USD',
    images: ['/products/grinder1.jpg'],
    status: 'visible',
    totalReports: 0,
    flaggedCount: 0,
    averageRating: 4.6,
    reviewCount: 201,
    visibility: 'public',
    featured: false,
    createdAt: new Date('2022-09-05'),
    updatedAt: new Date('2024-11-10'),
  },
  {
    id: 'p009',
    businessId: 'b009',
    businessName: 'CopyKick Store',
    name: 'Counterfeit Nike Air Force 1',
    description: '1:1 Clone Nike shoes. Exact replica with original box.',
    category: 'Fashion',
    price: 25.00,
    currency: 'USD',
    images: ['/products/shoes1.jpg'],
    status: 'banned',
    totalReports: 2,
    flaggedCount: 6,
    averageRating: 0,
    reviewCount: 0,
    visibility: 'hidden',
    featured: false,
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-03-13'),
    lastModeratedAt: new Date('2025-03-13'),
  },
  {
    id: 'p010',
    businessId: 'b010',
    businessName: 'OutdoorTech',
    name: 'Portable Solar Charger 20000mAh',
    description: 'Solar power bank with dual USB output. Water resistant. Perfect for hiking.',
    category: 'Electronics',
    price: 42.00,
    currency: 'USD',
    images: ['/products/solar1.jpg'],
    status: 'hidden',
    totalReports: 0,
    flaggedCount: 0,
    averageRating: 4.2,
    reviewCount: 87,
    visibility: 'private',
    featured: false,
    createdAt: new Date('2022-06-20'),
    updatedAt: new Date('2025-01-05'),
  },
];