# Generated by Django 6.0.2 on 2026-04-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('city', models.TextField()),
                ('status', models.TextField(choices=[('PENDING', 'En attente'), ('PUBLISHED', 'Publié'), ('REJECTED', 'Rejeté')], default='PENDING')),
                ('rne', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stores',
                'managed': False,
            },
        ),
    ]
